# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AlgorithmSupport.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AlgorithmSupport.proto',
  package='AlgorithmSupport',
  syntax='proto3',
  serialized_options=b'\n\020AlgorithmSupportB\025AlgorithmSupportProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x41lgorithmSupport.proto\x12\x10\x41lgorithmSupport\"\x81\x01\n\x17\x41lgorithmSupportRequest\x12\x13\n\x0bserviceType\x18\x01 \x01(\t\x12\x10\n\x08\x65ntityID\x18\x02 \x01(\t\x12\x16\n\x0estartTimestamp\x18\x03 \x01(\t\x12\x14\n\x0c\x65ndTimestamp\x18\x04 \x01(\t\x12\x11\n\talgorithm\x18\x05 \x01(\t\"*\n\x18\x41lgorithmSupportResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\x86\x01\n\x17\x41lgorithmSupportService\x12k\n\x10\x41lgorithmSupport\x12).AlgorithmSupport.AlgorithmSupportRequest\x1a*.AlgorithmSupport.AlgorithmSupportResponse\"\x00\x42+\n\x10\x41lgorithmSupportB\x15\x41lgorithmSupportProtoP\x01\x62\x06proto3'
)




_ALGORITHMSUPPORTREQUEST = _descriptor.Descriptor(
  name='AlgorithmSupportRequest',
  full_name='AlgorithmSupport.AlgorithmSupportRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='serviceType', full_name='AlgorithmSupport.AlgorithmSupportRequest.serviceType', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entityID', full_name='AlgorithmSupport.AlgorithmSupportRequest.entityID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='startTimestamp', full_name='AlgorithmSupport.AlgorithmSupportRequest.startTimestamp', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='endTimestamp', full_name='AlgorithmSupport.AlgorithmSupportRequest.endTimestamp', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='AlgorithmSupport.AlgorithmSupportRequest.algorithm', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=174,
)


_ALGORITHMSUPPORTRESPONSE = _descriptor.Descriptor(
  name='AlgorithmSupportResponse',
  full_name='AlgorithmSupport.AlgorithmSupportResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='AlgorithmSupport.AlgorithmSupportResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=218,
)

DESCRIPTOR.message_types_by_name['AlgorithmSupportRequest'] = _ALGORITHMSUPPORTREQUEST
DESCRIPTOR.message_types_by_name['AlgorithmSupportResponse'] = _ALGORITHMSUPPORTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AlgorithmSupportRequest = _reflection.GeneratedProtocolMessageType('AlgorithmSupportRequest', (_message.Message,), {
  'DESCRIPTOR' : _ALGORITHMSUPPORTREQUEST,
  '__module__' : 'AlgorithmSupport_pb2'
  # @@protoc_insertion_point(class_scope:AlgorithmSupport.AlgorithmSupportRequest)
  })
_sym_db.RegisterMessage(AlgorithmSupportRequest)

AlgorithmSupportResponse = _reflection.GeneratedProtocolMessageType('AlgorithmSupportResponse', (_message.Message,), {
  'DESCRIPTOR' : _ALGORITHMSUPPORTRESPONSE,
  '__module__' : 'AlgorithmSupport_pb2'
  # @@protoc_insertion_point(class_scope:AlgorithmSupport.AlgorithmSupportResponse)
  })
_sym_db.RegisterMessage(AlgorithmSupportResponse)


DESCRIPTOR._options = None

_ALGORITHMSUPPORTSERVICE = _descriptor.ServiceDescriptor(
  name='AlgorithmSupportService',
  full_name='AlgorithmSupport.AlgorithmSupportService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=221,
  serialized_end=355,
  methods=[
  _descriptor.MethodDescriptor(
    name='AlgorithmSupport',
    full_name='AlgorithmSupport.AlgorithmSupportService.AlgorithmSupport',
    index=0,
    containing_service=None,
    input_type=_ALGORITHMSUPPORTREQUEST,
    output_type=_ALGORITHMSUPPORTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ALGORITHMSUPPORTSERVICE)

DESCRIPTOR.services_by_name['AlgorithmSupportService'] = _ALGORITHMSUPPORTSERVICE

# @@protoc_insertion_point(module_scope)
