# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import powerpredict_pb2 as powerpredict__pb2


class PowerPredictServiceStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PowerPredict = channel.unary_unary(
                '/powerpredict.PowerPredictService/PowerPredict',
                request_serializer=powerpredict__pb2.PowerPredictRequest.SerializeToString,
                response_deserializer=powerpredict__pb2.PowerPredictReply.FromString,
                )


class PowerPredictServiceServicer(object):
    """The greeting service definition.
    """

    def PowerPredict(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PowerPredictServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PowerPredict': grpc.unary_unary_rpc_method_handler(
                    servicer.PowerPredict,
                    request_deserializer=powerpredict__pb2.PowerPredictRequest.FromString,
                    response_serializer=powerpredict__pb2.PowerPredictReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'powerpredict.PowerPredictService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PowerPredictService(object):
    """The greeting service definition.
    """

    @staticmethod
    def PowerPredict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/powerpredict.PowerPredictService/PowerPredict',
            powerpredict__pb2.PowerPredictRequest.SerializeToString,
            powerpredict__pb2.PowerPredictReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
