# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import powerevaluate_pb2 as powerevaluate__pb2


class PowerEvaluateServiceStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PowerEvaluate = channel.unary_unary(
                '/powerevaluate.PowerEvaluateService/PowerEvaluate',
                request_serializer=powerevaluate__pb2.PowerEvaluateRequest.SerializeToString,
                response_deserializer=powerevaluate__pb2.PowerEvaluateReply.FromString,
                )


class PowerEvaluateServiceServicer(object):
    """The greeting service definition.
    """

    def PowerEvaluate(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PowerEvaluateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PowerEvaluate': grpc.unary_unary_rpc_method_handler(
                    servicer.PowerEvaluate,
                    request_deserializer=powerevaluate__pb2.PowerEvaluateRequest.FromString,
                    response_serializer=powerevaluate__pb2.PowerEvaluateReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'powerevaluate.PowerEvaluateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PowerEvaluateService(object):
    """The greeting service definition.
    """

    @staticmethod
    def PowerEvaluate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/powerevaluate.PowerEvaluateService/PowerEvaluate',
            powerevaluate__pb2.PowerEvaluateRequest.SerializeToString,
            powerevaluate__pb2.PowerEvaluateReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
